services:
  code:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        NODE_VERSION: 20
        MONGODB_CLI_VERSION: "6.0"
    container_name: carddavplay-code
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
