services:
  code:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        NODE_VERSION: 20
    container_name: carddav-play
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
